services:
  base:
    image: mariadb
    # restart: always
    environment: 
      MYSQL_DATABASE: proyecto
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes: 
      - .database/:/var/lib/mysql
    expose:
      - 3312
    ports:
      - "3388:3306"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8787:8787
    volumes: 
      - .:/proyecto
    depends_on:
      - base
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  .database: