# Generated by Django 3.2.3 on 2021-05-25 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserv',
            name='clase',
        ),
        migrations.RemoveField(
            model_name='reserv',
            name='profesor',
        ),
        migrations.DeleteModel(
            name='Clase',
        ),
        migrations.DeleteModel(
            name='Reserv',
        ),
    ]
