# Generated by Django 3.2.3 on 2021-05-26 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_auto_20210525_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('image', models.ImageField(upload_to='clases')),
                ('image2', models.ImageField(upload_to='clases')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservationday', models.DateField()),
                ('horainicio', models.CharField(max_length=2)),
                ('horafinal', models.CharField(max_length=2)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('curso', models.CharField(max_length=6)),
                ('motivo', models.CharField(max_length=150)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.clase')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profesor')),
            ],
        ),
        migrations.AddField(
            model_name='clase',
            name='reservas',
            field=models.ManyToManyField(through='reserva.Reserv', to='app.Profesor'),
        ),
    ]
