# Generated by Django 3.2.3 on 2021-05-31 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserv',
            name='horafinal',
            field=models.DateTimeField(max_length=2),
        ),
        migrations.AlterField(
            model_name='reserv',
            name='horainicio',
            field=models.DateTimeField(max_length=2),
        ),
    ]
