# Generated by Django 3.2.3 on 2021-06-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0002_auto_20210531_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserv',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
